language: python
matrix:
  include:
    - name: "Python 3.5 on Windows"
      os: windows
      language: sh
      python: "3.5"
      before_install:
        - choco install python3 --version 3.5
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - name: "Python 3.6 on Windows"
      os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python3 --version 3.6.0
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"   
    - name: "Python 3.7 on Windows"
      os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"   		
# install dependencies
install:
  - python --version
# run tests
script:
  - python -m unittest discover -s $TRAVIS_BUILD_DIR/tests -t $TRAVIS_BUILD_DIR/tests